# Generated by Django 4.2.7 on 2023-12-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_article_articlecategory_course_courseheading_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
